name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_APP}}
          heroku_app_name: "brainhack-dataviz" #Must be unique in Heroku
          heroku_email: "balletviolin15@gmail.com"
